version: "3.8"

services:
  keepiprog:
    build:
      context: ./            # Donde est√°n el Dockerfile y KeepiProg.csproj
      dockerfile: Dockerfile
    ports:
      - "8080:80"            # http://localhost:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Keepi_DataBase;User Id=sa;Password=YoSoyKeepiYVosNo4732;TrustServerCertificate=True;
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YoSoyKeepiYVosNo4732
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql   # Datos de la BD persistentes

volumes:
  sql_data:
